## Introduction

## Data cleaning

### Similar columns

According to description of fields from the provided documentation :  

> "fields that end with _tags are comma separated list of tags (e.g. categories_tags is the set of normalized tags computed from the categories field)"

Therefore, when several columns contain the same data ("countries", "countries_tags" and "countries_fr" for example), the column wth suffix "_tags" will be preferred because it is normalized.

However, some similar columns do not have the same amount of non-null values.

In [ ]:
def compare_similar_columns_missing_values(df:pd.DataFrame, base_col_name:str, include_columns:list[str]=["product_name"], exclude_columns:list[str]=[]):
    # Get other simimar columns
    columns = [c for c in products if c.startswith(base_col_name) and c not in exclude_columns]

    # Look for products with at least 1 missing value among the columns AND 1 non missing value among the columns
    n_values = df[columns].count(axis=1) # Count non missing values among the columns
    condition = np.logical_and(1 <= n_values, n_values < len(columns)) # Build the condition

    return df.loc[condition, include_columns + columns] # Return products matching the condition

In [ ]:
compare_similar_columns_missing_values(df=products, base_col_name="brands")

                                        product_name brands brands_tags
181735                                  Grana padano      ?         NaN
184680                          Wortel selder salade      /         NaN
186293                            Camembert rustique      /         NaN
191650          Le Centurion Emmental En Tranchettes     ??         NaN
214423                                 Lait fermenté     --         NaN
234196                         Mami nova gourmand         .         NaN
248209  [n. a!] Nature Addicts Rice Crackers Paprika    NaN          na
248211                             My mix Blue Boost    NaN          na
251872                         Muffins bio au seigle      ?         NaN
264490                         Deutsche Markenbutter      -         NaN
304532                        sugo al Nero Di seppie      ?         NaN
306140                       Mini crackers cocktail       ?         NaN

### Contexte

L'agence Santé publique France souhaite améliorer sa base de données Open Food Facts et fait appel aux services de votre entreprise. Cette base de données open source est mise à la disposition de particuliers et d’organisations afin de leur permettre de connaître la qualité nutritionnelle de produits. 
 
Aujourd’hui, pour ajouter un produit à la base de données d'Open Food Facts, il est nécessaire de remplir de nombreux champs textuels et numériques, ce qui peut conduire à des erreurs de saisie et à des valeurs manquantes dans la base. 

L’agence Santé publique France confie à votre entreprise la création d’un système de suggestion ou d’auto-complétion pour aider les usagers à remplir plus efficacement la base de données. Dans un premier temps, vous devez vous concentrer sur la prise en main des données, et d’abord les nettoyer et les explorer. 

### Problématique

__Est-il possible de suggérer des valeurs pour certains champs lors de l'ajout d'un nouveau produit afin de réduire les erreurs de saisie et les valeurs manquantes dans la base de données Open Food Facts ?__

### Objectifs

- Identifier les variables cibles pour lesquelles il serait pertinent de suggérer des valeurs (plus de 50% de valeurs manquantes).
- Identifier les variables nécessaires pour lesquelles il est important d'avoir des données.
- Filtrer 
- Mettre en évidence les valeurs manquantes
- Identifier 3 méthodes adaptées (métiers) pour traiter ces valeurs manquantes.
- Automatiser les traitements pour éviter de répéter les opérations.


- Se servir de ces variables nécessaires pour tenter de faire des suggestions sur les variables avec des valeurs manquantes.

- Etablir la faisabilité de suggérer les valeurs manquantes pour une variable dont plus de 50% des valeurs sont manquantes.

### About RGPD

- Expliquer que la RGPD ne s'applique que dans le cadre de la manipulation de données personnelles.
- Détailler les grands principes des RGPD et en quoi ce projet reste tout de même cohérent avec ces principes.
- Expliquer ce qu'et une donnée personnelle et conclure que dans ce projet n'a pas de lien avec les RGPD.

## Imports and setup

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Optional, Callable
import missingno as msno

In [2]:
# Data collection
products = pd.read_csv('fr.openfoodfacts.org.products.csv', sep="\t", low_memory=True)

# Using low_memory = False to remove the DTypeWarning resulted in "code" column being modified.
# For example :
# low_memory = True : 11778, 11778
# low_memory = False : 0011778, 00011778
# Duplicates seem to all be removed like this with low_memory = False

C:\Users\HCYF5290\AppData\Local\Temp\1\ipykernel_12720\3569971905.py:2: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,35,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  products = pd.read_csv('fr.openfoodfacts.org.products.csv', sep="\t", low_memory=True)

In [ ]:
# Data collection

# Using low_memory = False to remove the DTypeWarning resulted in "code" column being modified.
# For example :
# low_memory = True : 11778, 11778
# low_memory = False : 0011778, 00011778
# All duplicates seem to be removed like this with low_memory = False

# Keeping low_memory = True could be troublesome since it causes some columns to have mixed types

# In order to avoid any issue, dtypes of object columns is forced on read_csv.

# Collect data and store it in a DataFrame
products = pd.read_csv('fr.openfoodfacts.org.products.csv', sep="\t", low_memory=True)

# Define columns to convert to string to prevent mixed types
columns_to_convert = [
    'code', 'url', 'creator', 'created_t', 'created_datetime',
    'last_modified_t', 'last_modified_datetime', 'product_name',
    'generic_name', 'quantity', 'packaging', 'packaging_tags',
    'brands', 'brands_tags', 'categories', 'categories_tags',
    'categories_fr', 'origins', 'origins_tags', 'manufacturing_places',
    'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_fr',
    'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities',
    'cities_tags', 'purchase_places', 'stores', 'countries',
    'countries_tags', 'countries_fr', 'ingredients_text', 'allergens',
    'allergens_fr', 'traces', 'traces_tags', 'traces_fr', 'serving_size',
    'additives', 'additives_tags', 'additives_fr', 'ingredients_from_palm_oil_tags',
    'ingredients_that_may_be_from_palm_oil_tags', 'nutrition_grade_fr',
    'pnns_groups_1', 'pnns_groups_2', 'states', 'states_tags', 'states_fr',
    'main_category', 'main_category_fr', 'image_url', 'image_small_url'
]

# Convert specified columns to string, preserving NaN
for column in columns_to_convert:
    products[column] = products[column].astype('object')

In [3]:
# Set the seaborn theme for plots
sns.set_theme(palette="dark")

In [ ]:
for col in products.columns:
    if products[col].dtype == "object":
        print(f"'{col}': 'object',")

In [ ]:
# Automatically get info about each variable of a given dataframe. Returns a dataframe.
def get_df_variables_info(df: pd.DataFrame) -> pd.DataFrame:
    
    # Get the shape of the DataFrame
    (n_rows, n_columns) = df.shape
    df_info = []

    # Sensitivity for top common values (15%). Used to highlight if most common values actually represent a significant proportion of the values.
    top_common_values_sensitivity = 0.15
    
    # Iterate over each column in the DataFrame
    for i, col in enumerate(df.columns):
        df_info.append({})
        # Count occurrences of each value in the column
        value_counts = df.value_counts(col)
        # Get the column type
        col_type = df[col].dtype
        # Count null values in the column
        n_null_values = df.isnull().sum()[col]
        # Count unique values
        n_unique_values = len(value_counts)
        # Count non-null values
        n_values = n_rows - n_null_values
        # Get the mode of the column
        mode = df[col].mode().values
        
        # Print basic information about the column
        df_info[i]["column_name"] = col
        df_info[i]["column_type"] = col_type
        df_info[i]["missing_value_percentage"] = round(n_null_values/n_rows*100, 2)

        # Proceed if there are non-null values
        if n_values != 0:
            df_info[i]["nbr_unique_values"] = n_unique_values
            df_info[i]["nbr_non_null_values"] = n_values 
            df_info[i]["duplicates_percentage"] = round(100-n_unique_values/n_values*100, 2)

            # If the column has fewer than 6 unique values, print their counts
            if n_unique_values < 6:
                df_info[i]["unique_values"] = ", ".join(f"{value_counts.index[i]} ({v} occurrences)" for i, v in enumerate(value_counts))

            # If the column type is numeric, gather statistical info
            if np.issubdtype(col_type, np.number):
                # Calculate quantiles, ignoring NaN values
                quantiles = np.quantile(df[col].dropna(), np.array([0.0, 0.25, 0.5, 0.75, 1.0]))
                mean = round(df[col].mean(), 2)
                
                # Print statistical summary
                df_info[i]["mean"] = mean
                df_info[i]["min"] = df[col].min()
                df_info[i]["max"] = df[col].max()
                df_info[i]["median"] = df[col].median()
                df_info[i]["std"] = round(df[col].std(ddof=1), 2)

                # # Create a boxplot for the column
                # fig, ax = plt.subplots(figsize=(9, 3))
                # ax.boxplot(df[col].dropna(), vert=False, showmeans=True, 
                #            meanprops={"markerfacecolor":'white', "marker":'o', "markeredgecolor":'firebrick', "markersize":8})

                # # Customize the plot
                # ax.grid(visible=False)

                # # Draw quantiles as vertical lines
                # ax.vlines(quantiles, [0]*quantiles.size, [1]*quantiles.size, color='chocolate', ls=':', lw=1, zorder=0)
                # ax.set_ylim(0.5, 1.5)
                # ax.set_yticklabels([])  # Hide y-tick labels
                # ax.set_xticks(quantiles)  # Set x-ticks to quantiles

                # # Annotate mean value next to the mean marker
                # ax.text(mean, 1.1, f'Mean: {round(mean, 2)}', color='firebrick', ha='center', fontsize=10)

                # # Set the plot title
                # plt.title(f"Distribution of column '{col}'")
                # plt.show()

            # Print the mode of the column
            df_info[i]["mode"] = f"""{", ".join(str(v) if i < 3 else f"... ({len(mode)} elements)" for i, v in enumerate(mode[:min(len(mode), 4)]))} ({value_counts.values[0]} occurrence(s))"""

            # Calculate top common values based on sensitivity
            n_top_common_values = int(len(value_counts) * top_common_values_sensitivity)
            top_common_values = value_counts.values[:n_top_common_values]
            
            # Check if the top common values represent a significant proportion of the data
            if value_counts.quantile(1 - top_common_values_sensitivity) / value_counts.max() < 0.25 and n_top_common_values <= 10:
                sum_top_common_values = top_common_values.sum()
                top_common_values_prop = round(sum_top_common_values / n_values, 2)
                top_common_values_info = [f"{value_counts.index[i]} ({value})" for i, value in enumerate(top_common_values)]
                
                # Print additional comments on common values
                df_info[i]["additional_comment"] = f"""First {n_top_common_values} unique values represent {top_common_values_prop * 100}% of total values : {', '.join(top_common_values_info)}"""
        else:
            # Inform if the column only contains null values
            df_info[i]["additional_comment"] = "This column only contains null values."

    return pd.DataFrame(df_info)

In [ ]:
# Visualize correlation of missing values between column pairs
# 1 means : if one variable is PRESENT then the other variable is very likely to be PRESENT.
# -1 means : if one variable is PRESENT then the other variable is very likely to be MISSING.
# 0 means : No dependance between occurence of missing values of the 2 columns.
msno.heatmap(filtered_data, figsize=(60,30))

In [ ]:
def _dfs(mat, pos, r_sum, c_sum, p_0, p):

    (xx, yy) = pos
    (r, c) = (len(r_sum), len(c_sum))

    mat_new = []

    for i in range(len(mat)):
        temp = []
        for j in range(len(mat[0])):
            temp.append(mat[i][j])
        mat_new.append(temp)

    if xx == -1 and yy == -1:
        for i in range(r-1):
            temp = r_sum[i]
            for j in range(c-1):
                temp -= mat_new[i][j]
            mat_new[i][c-1] = temp
        for j in range(c-1):
            temp = c_sum[j]
            for i in range(r-1):
                temp -= mat_new[i][j]
            mat_new[r-1][j] = temp
        temp = r_sum[r-1]
        for j in range(c-1):
            temp -= mat_new[r-1][j]
        if temp <0:
            return
        mat_new[r-1][c-1] = temp

        p_1 = 1
        for x in r_sum:
            p_1 *= math.factorial(x)
        for y in c_sum:
            p_1 *= math.factorial(y)

        n = 0
        for x in r_sum:
            n += x
        p_1 /= math.factorial(n)

        for i in range(len(mat_new)):
            for j in range(len(mat_new[0])):
                p_1 /= math.factorial(mat_new[i][j])
        if p_1 <= p_0 + 0.00000001:
            #print(mat_new)
            #print(p_1)
            p[0] += p_1
    else:
        max_1 = r_sum[xx]
        max_2 = c_sum[yy]
        for j in range(c):
            max_1 -= mat_new[xx][j]
        for i in range(r):
            max_2 -= mat_new[i][yy]
        for k in range(min(max_1,max_2)+1):
            mat_new[xx][yy] = k
            if xx == r-2 and yy == c-2:
                pos_new = (-1, -1)
            elif xx == r-2:
                pos_new = (0, yy+1)
            else:
                pos_new = (xx+1, yy)
            _dfs(mat_new, pos_new, r_sum, c_sum, p_0, p)


def fisher_exact(table):

    row_sum = []
    col_sum = []

    for i in range(len(table)):
        temp = 0
        for j in range(len(table[0])):
            temp += table[i][j]
        row_sum.append(temp)
    
    for j in range(len(table[0])):
        temp = 0
        for i in range(len(table)):
            temp += table[i][j]
        col_sum.append(temp)

    mat = [[0] * len(col_sum)] * len(row_sum)
    pos = (0, 0)

    p_0 = 1

    for x in row_sum:
        p_0 *= math.factorial(x)
    for y in col_sum:
        p_0 *= math.factorial(y)

    n = 0
    for x in row_sum:
        n += x
    p_0 /= math.factorial(n)

    for i in range(len(table)):
        for j in range(len(table[0])):
            p_0 /= math.factorial(table[i][j])

    p = [0]
    _dfs(mat, pos, row_sum, col_sum, p_0, p)

    return p[0]

In [ ]:
def chi_squared(data:pd.DataFrame, x:str, y:str):
    contingency_table = data[[x,y]].dropna().pivot_table(index=x,columns=y,aggfunc=len) 
    contingency_table.fillna(0, inplace=True)
    results = stats.chi2_contingency(observed=contingency_table)
    #print(contingency_table.to_numpy(dtype=int))
    return results

In [ ]:
test = products.dropna(subset="pnns_groups_1")
test = test[["cities_tags", "pnns_groups_1"]].dropna()
test["cities_tags"] = test["cities_tags"].str.split(',')
test = test.explode("cities_tags")
chi_squared(products.dropna(subset="pnns_groups_1"), "pnns_groups_2", "pnns_groups_1")

In [ ]:
chi_squared(products.dropna(subset="pnns_groups_1"), "pnns_groups_2", "pnns_groups_1")

In [ ]:
f_value = f_classif(features_data, target_series)

for feature in zip(features_data.columns, f_value[0]) :
        print(feature)

In [ ]:
    # always_relevant_columns = ["code", "product_name", "brands_tags", "energy_100g", "carbohydrates_100g", "fat_100g", "fiber_100g", "proteins_100g", "saturated-fat_100g", "sugars_100g", 'pnns_groups_1','pnns_groups_2']

## Data cleaning

### Similar columns

According to description of fields from the provided documentation :  

> "fields that end with _tags are comma separated list of tags (e.g. categories_tags is the set of normalized tags computed from the categories field)"

Therefore, when several columns contain the same data ("countries", "countries_tags" and "countries_fr" for example), the column wth suffix "_tags" will be preferred because it is normalized.

However, some similar columns do not have the same amount of non-null values.

In [ ]:
def compare_similar_columns_missing_values(df:pd.DataFrame, base_col_name:str, include_columns:list[str]=["product_name"], exclude_columns:list[str]=[]):
    # Get other simimar columns
    columns = [c for c in products if c.startswith(base_col_name) and c not in exclude_columns]

    # Look for products with at least 1 missing value among the columns AND 1 non missing value among the columns
    n_values = df[columns].count(axis=1) # Count non missing values among the columns
    condition = np.logical_and(1 <= n_values, n_values < len(columns)) # Build the condition

    return df.loc[condition, include_columns + columns] # Return products matching the condition

In [ ]:
compare_similar_columns_missing_values(df=products, base_col_name="brands")

                                        product_name brands brands_tags
181735                                  Grana padano      ?         NaN
184680                          Wortel selder salade      /         NaN
186293                            Camembert rustique      /         NaN
191650          Le Centurion Emmental En Tranchettes     ??         NaN
214423                                 Lait fermenté     --         NaN
234196                         Mami nova gourmand         .         NaN
248209  [n. a!] Nature Addicts Rice Crackers Paprika    NaN          na
248211                             My mix Blue Boost    NaN          na
251872                         Muffins bio au seigle      ?         NaN
264490                         Deutsche Markenbutter      -         NaN
304532                        sugo al Nero Di seppie      ?         NaN
306140                       Mini crackers cocktail       ?         NaN

In [ ]:
def imputation(df:pd.DataFrame, features_to_estimate:list[str], group_columns:list[str], method:Callable=np.mean):
    '''
    Imputes missing values for specified features in a DataFrame using group averages or a specified method.

    Parameters:
    df (pd.DataFrame): Original DataFrame.
    features_to_estimate (str): Features for which missing data needs to be imputed.
    group_columns (str): Possible grouping variables for aggregation. All combinations will be attempted and the one with the lowest variation will be chosen for each missing value.
    method (Callable): Imputation method (e.g., mean, median). Defaults to np.mean.

    Returns:
    pd.DataFrame: DataFrame with imputed values for the specified indicator.
    '''
    if not set(group_columns).issubset(df.columns):
        raise ValueError("Argument 'group_columns' should only contain valid 'df' columns")
    
    df_copy = df.copy()

    df_copy.loc[:, "group_id_set"] = df_copy.loc[:, group_columns].fillna('nan').apply(set, axis=1)

    missing_data = df_copy.loc[df_copy[features_to_estimate].isna().any(axis=1)]

    filtered_df = df_copy.loc[df_copy["group_id_set"].isin()]
    

    missing_data.loc[:, "group_id_set"] = missing_data.loc[:, group_columns].fillna('nan').apply(set, axis=1)

    df_cvs_medians = pd.DataFrame()

    # Partial function for method_if_criteria_met
    method_func = partial(method_if_criteria_met, method=method)

    for i in range(1, len(group_columns) + 1):
        for combo in combinations(group_columns, i):
            print(f'''Processing combination: "{'", "'.join(list(combo))}"''')
            df_copy["group_id"] = df_copy[list(combo)].fillna('nan').agg("_|_".join, axis=1)

            # Group by current combination and apply the function
            group = df_copy[["group_id"] + features_to_estimate].groupby("group_id").agg([coef_var, method_func])

            if df_cvs_medians.empty:
                df_cvs_medians = group
            else:
                df_cvs_medians = pd.concat([df_cvs_medians, group])

    df_cvs_medians = df_cvs_medians.dropna(how="all")

    for i in missing_data.index:
        group_id_set = missing_data.loc[i, "group_id_set"]
        matching_rows = df_cvs_medians.loc[df_cvs_medians.index.map(lambda x: set(x.split("_|_")).issubset(group_id_set))]

        missing_features = missing_data[features_to_estimate].loc[i].isna().index
        
        for feature in missing_features:
            sub_df = matching_rows[feature]
            values = sub_df.loc[sub_df["coef_var"] == sub_df["coef_var"].min(), "method_if_criteria_met"].values
            if len(values) > 0:
                df_copy.loc[i, feature] = values[0]

    return df_copy